name: Verify CodeDeploy Deployment

on:
  workflow_run:
    workflows: ["AWS Pipeline"]
    types:
      - completed

jobs:
  verify_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your desired region

      - name: Get Deployment Status
        id: get_deployment
        run: |
          deployment_id="<your-deployment-id>"  # Replace with your actual deployment ID
          deployment_status=$(aws deploy get-deployment --deployment-id $deployment_id --query "deploymentInfo.status" --output text)
          echo "Deployment status: $deployment_status"
          echo "::set-output name=status::$deployment_status"

      - name: Verify Deployment Status
        run: |
          deployment_status="${{ steps.get_deployment.outputs.status }}"
          if [[ "$deployment_status" == "Succeeded" ]]; then
            echo "CodeDeploy deployment succeeded!"
          else
            echo "CodeDeploy deployment failed!"
            exit 1
          fi
